# ======================================================================
# Combined XRBitcoinCash + XRBitcoin discoverable TOML
# Domain: xrbitcoincash.com  (primary Web2 host)
# Published: 2025-10-08 (update as needed)
# ======================================================================

# ----------------------
# Root account info (primary operator)
# ----------------------
[meta]
name        = "XRBitcoin Ecosystem"
domain      = "xrbitcoincash.com"
website     = "https://xrbitcoincash.com/"
logo        = "https://xrbitcoincash.com/XRBitcoin/xrbitcoin-logo.png"
description = "XRBitcoinCash and XRBitcoin projects — XRPL tokens built for transparency, security, and discoverability. Web2 + Web3 identity strategy in place."

[social]
twitter   = "@XRbitcoincash"
email     = "xrbitcoincash@gmail.com"
github    = "https://github.com/XRBitcoinCash"
xpmarket  = "https://xpmarket.com/token/XRbitcoin-rGQaHbQHCsTLQtboQPwUBasXjLvk8uDbpT"
sologenic = "https://sologenic.org/"

# ----------------------
# Accounts (both issuers)
# ----------------------
[[ACCOUNTS]]
address = "rEjwniYhYR5QDZzK1a1x2359j8j8N43Ypw"
network = "main"
desc    = "XRBitcoinCash Issuer (blackholed)"

[[ACCOUNTS]]
address = "rGQaHbQHCsTLQtboQPwUBasXjLvk8uDbpT"
network = "main"
desc    = "XRBitcoin Issuer (blackholed, fixed supply)"

# ----------------------
# XRBitcoinCash token block (existing)
# ----------------------
[[CURRENCIES]]
currency         = "5852626974636F696E6361736800000000000000"
issuer           = "rEjwniYhYR5QDZzK1a1x2359j8j8N43Ypw"
name             = "XRBitcoinCash"
desc             = "XRBitcoinCash (XRBC) — community-focused XRPL asset."
icon             = "https://xrbitcoincash.com/xrbc-nft.png"
network          = "main"
display_decimals = 6

[[CURRENCIES.links]]
url   = "https://xrbitcoincash.com/"
title = "XRBitcoinCash Official Site"
type  = "website"

# ----------------------
# XRBitcoin token block (new)
# ----------------------
[[CURRENCIES]]
code             = "XRBitcoin"
currency         = "5852626974636F696E0000000000000000000000"
issuer           = "rGQaHbQHCsTLQtboQPwUBasXjLvk8uDbpT"
name             = "XRBitcoin"
desc             = "XRBitcoin (XRBTC) — fixed-supply XRPL asset, derived from XRBitcoinCash framework."
icon             = "https://xrbitcoincash.com/XRBitcoin/xrbitcoin-logo.png"
network          = "main"
display_decimals = 6

[[CURRENCIES.links]]
url   = "https://xrbitcoincash.com/XRBitcoin/"
title = "XRBitcoin Official Site"
type  = "website"

[[CURRENCIES.links]]
url   = "https://xpmarket.com/token/XRbitcoin-rGQaHbQHCsTLQtboQPwUBasXjLvk8uDbpT"
title = "XPMarket Listing"
type  = "exchange"

[[CURRENCIES.links]]
url   = "https://sologenic.org/trade?market=5852626974636F696E0000000000000000000000%2BrGQaHbQHCsTLQtboQPwUBasXjLvk8uDbpT%2FXRP"
title = "Sologenic DEX Market"
type  = "exchange"

[[CURRENCIES.links]]
url   = "https://sologenic.org/nfts/rUh5JLJNQ3NhwvHCPxgt8myXx22j1bWw1a"
title = "XRBitcoin NFT Collection"
type  = "nft"

# ----------------------
# Optional server (public node info)
# ----------------------
[[SERVERS]]
json_rpc = "https://xrplcluster.com/"
network  = "main"
desc     = "Public read-only XRPL endpoint"

# ----------------------
# DID / Web3 pointer (add your Web3 domain / DID here)
# ----------------------
[DID]
id  = "did:web:unstoppable:xrbitcoin.crypto" # replace with your chosen Web3 DID / ENS / Unstoppable id
url = "https://xrbitcoincash.com/"

# ======================================================================
# NOTE:
# - Host this file exactly at: https://xrbitcoincash.com/.well-known/xrp-ledger.toml
# - If you want XRBitcoin to be independent, host its TOML on a separate custom domain/subdomain
# ======================================================================
